ALTER TABLE "productos"
  ADD COLUMN "controla_stock" BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE "productos" AS p
SET "controla_stock" = FALSE
FROM "unidad" AS u
WHERE p."id_unidad" = u."id_unidad"
  AND lower(trim(u."unidad")) = 'por peso variable';

CREATE TABLE "venta" (
  "id_venta" UUID NOT NULL DEFAULT gen_random_uuid(),
  "num_venta" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "id_vendedor" UUID NOT NULL,
  "valor_total" INTEGER NOT NULL,
  "fecha_de_creacion" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_pago" TIMESTAMPTZ(6),
  "estado" VARCHAR(30) NOT NULL,
  "vuelto" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT "venta_pkey" PRIMARY KEY ("id_venta"),
  CONSTRAINT "venta_num_venta_key" UNIQUE ("num_venta"),
  CONSTRAINT "venta_valor_total_check" CHECK ("valor_total" >= 0),
  CONSTRAINT "venta_vuelto_check" CHECK ("vuelto" >= 0),
  CONSTRAINT "fk_venta_vendedor" FOREIGN KEY ("id_vendedor") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE "detalle" (
  "id_detalle" UUID NOT NULL DEFAULT gen_random_uuid(),
  "id_venta" UUID NOT NULL,
  "id_producto" UUID NOT NULL,
  "costo_adquisicion_actual" INTEGER NOT NULL,
  "cantidad" NUMERIC(12, 3) NOT NULL,
  "precio_actual" INTEGER NOT NULL,
  "subtotal_venta" INTEGER NOT NULL,
  CONSTRAINT "detalle_pkey" PRIMARY KEY ("id_detalle"),
  CONSTRAINT "detalle_cantidad_check" CHECK ("cantidad" > 0),
  CONSTRAINT "detalle_costo_check" CHECK ("costo_adquisicion_actual" >= 0),
  CONSTRAINT "detalle_precio_check" CHECK ("precio_actual" >= 0),
  CONSTRAINT "detalle_subtotal_check" CHECK ("subtotal_venta" >= 0),
  CONSTRAINT "fk_detalle_venta" FOREIGN KEY ("id_venta") REFERENCES "venta"("id_venta") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "fk_detalle_producto" FOREIGN KEY ("id_producto") REFERENCES "productos"("id_productos") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX "detalle_id_venta_idx" ON "detalle"("id_venta");

CREATE TABLE "pagos" (
  "id_pago" UUID NOT NULL DEFAULT gen_random_uuid(),
  "id_venta" UUID NOT NULL,
  "id_medio_pago" UUID NOT NULL,
  "pago" INTEGER NOT NULL,
  CONSTRAINT "pagos_pkey" PRIMARY KEY ("id_pago"),
  CONSTRAINT "pagos_pago_check" CHECK ("pago" > 0),
  CONSTRAINT "fk_pagos_venta" FOREIGN KEY ("id_venta") REFERENCES "venta"("id_venta") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "fk_pagos_medio_pago" FOREIGN KEY ("id_medio_pago") REFERENCES "medio_pago"("id_medio") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX "pagos_id_venta_idx" ON "pagos"("id_venta");
